[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38', 'py39', 'py310', 'py310']

[tool.pytest.ini_options]
filterwarnings = [
    "error:::marshmallow_dataclass|test",
]

[tool.mypy]
packages = [
    "marshmallow_dataclass",
    "tests",
]
# XXX: Specifying the marshmallow_dataclass.mypy plugin directly by
# module name or by path does not work when running mypy from pre-commit.
# (See the docstring in mypy_plugin.py for more.)
plugins = "mypy_plugin.py"

warn_redundant_casts = true
warn_unused_configs = true
disable_error_code = "annotation-unchecked"

[[tool.mypy.overrides]]
# dependencies without type hints
module = [
    "marshmallow_enum",
    "typing_inspect",
]
ignore_missing_imports = true

